### ISSUE TITLE
2018.01 error on start : lpstools.nodeConfigurator has not attribute MODE_TWR_ANCOR

### ISSUE THREAD

**Issue by benkuper** [bitcraze/lps-tools#11]
![2018-05-14 12_10_24-new issue bitcraze_lps-tools](https://user-images.githubusercontent.com/1291595/40009378-d0727294-576f-11e8-91ea-e61d65de6c21.png)

Reinstalling it didn't fix the problem

**Comment by ataffanel** [comment]
I cannot reproduce the error on a fresh Windows 10 machine.

Do you have lpstools install as a pip package in your windows machine as well? It should not be possible bu it might be that the executable is trying to run your locally-installed version.

**Comment by krichardsson** [comment]
Can not reproduce.
