### ISSUE TITLE
LPS tool crashing on Mac when node in DFU-mode

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/lps-tools#18]
The LPS tool crashes as soon as the node enters DFU mode.

How to reproduce 1:
1. Start LPS-tools
2. Hold the DFU button and insert USB cable in node
Result: LPS tools terminate

How to reproduce 2:
1. Start LPS-tools
2. Insert USB cable in node (do not hold DFU button)
3. Re-boot anchor holding DFU-button
Result: LPS tools terminate

System info:
OSX 11.3, Intel core i5
PyQt5                  5.15.2
pyserial               3.5

Output in termina:
```
Kristoffers-MBP:lps-tools kristoffer$ python3 -m lpstools
Assertion failed: (NULL == darwin_cached_devices.next), function darwin_init, file os/darwin_usb.c, line 584.
Abort trap: 6
```

**Comment by krichardsson** [comment]
@MonaNekoWR since you fond problems (in #14), Is this the behaviour you observe as well?

**Comment by MonaNekoWR** [comment]
> @MonaNekoWR since you fond problems (in #14), Is this the behaviour you observe as well?

Well, it isn't.
But I think you can use ls and screen command directly in terminal to test the nodes.

**Comment by krichardsson** [comment]
This problem was probably caused by an update of OSX. It was fixed by reinstalling libusb and pyusb.
```
pip uninstall pyusb
brew uninstall libusb
brew install libusb
pip install pyusb
```
