### ISSUE TITLE
requirements do not fit other bitcraze repos

### ISSUE THREAD

**Issue by dominiknatter** [bitcraze/lps-tools#20]
Hey everyone,

While following [your tutorial about the loco positioning system](https://www.bitcraze.io/documentation/tutorials/getting-started-with-loco-positioning-system/) I stumbled across a requirements mismatch. I first installed the cfclient, which [requires](https://github.com/bitcraze/crazyflie-clients-python/blob/master/setup.py#L144) pyserial 3.5.x. I later installed the lps-tools repo, which [requires](https://github.com/bitcraze/lps-tools/blob/master/setup_common.py#L12) pyserial 3.4. Due to [recent changes](https://github.com/pypa/pip/issues/7744) in the behavior of pip, this lead to overwriting my pyserial version 3.5 with 3.4 and printed
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cfclient 2021.4.post13+f25f72d requires pyserial~=3.5, but you have pyserial 3.4 which is incompatible.`

I circumvented this problem by adapting the requirements for lps-tools by using `pyserial>=3.4` instead of `pyserial==3.4` and then installed both cfclient and lps-tools anew. So far I have not encountered any problem with this setup.

Not sure you wanna adapt my "solution", but at least this issue documents the problem for other users.

**Comment by krichardsson** [comment]
Good catch!

We should probably change it to ```pyserial~=3.4``` to avoid acceptance of 4.0 in the future.
