### ISSUE TITLE
update button unresponsive

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/lps-tools#21]
The loco tool does detect when the Loco node is in dfu mode, however the Update button is grayed out which makes it not possible to update the Loco node

![image](https://user-images.githubusercontent.com/11061260/150974020-55349a6f-13b5-4365-bb6c-15264e08e110.png)

**Comment by knmcguire** [comment]
Just a classic case of not reading the doc :smile: I didn't add the usb rights in udev as I'm using ubuntu 20.04.

**Comment by matejkarasek** [comment]
Also on Windows you might experience this, the solution is also in the docs (install the driver only after switching to DFU/bootloader): https://www.bitcraze.io/documentation/repository/lps-node-firmware/master/building/zadig_lps/
